export const constants = {
    secureStore_authenticatedUsers: 'authenticatedUsers',
    secureStore_authenticatedUsersEncryptionKeys: 'authenticatedUsersEncryptionKeys',
    localStorage_publicKey: 'publicKey',
    localStorage_termsAccepted: 'termsAccepted',
    localStorage_appearance: '_appearance',
    localStorage_lastSentNotification: 'lastSentNotification',
    localStorage_readonly: 'readonly',
    localStorage_messagesFilter: '_messagesFilter',
    localStorage_messagesSort: '_messagesSort',
    localStorage_cloutCastFeedFilter: '_cloutCastFeedFilter',
    localStorage_cloutCastFeedSort: '_cloutCastFeedSort',
    localStorage_defaultFeed: '_defaultFeed',
    localStorage_cloutCastFeedEnabled: '_cloutCastFeedEnabled',
    localStorage_cloutFeedHapticsEnabled: '_cloutFeedHapticsEnabled',
    localStorage_cloutFeedIdentity: 'cloutfeedIdentity',
    localStorage_showNotificationsFilter: 'showNotificationsFilter',
    localStorage_notificationsFilter: 'notificationsFilter',
    localStorage_cloutCastIntroduction: 'cloutCastIntroduction',
    cloutfeed_publicKey: 'BC1YLh5pKXs8NqaUtN8Gzi3rfoAgG2VWio2NER7baDkG8T2x7wRnSwa',
}
